# Generated by Django 3.0.4 on 2020-03-21 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_played',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 22, 26, 25, 816566, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='history',
            name='score_player_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='score_player_2',
            field=models.IntegerField(default=0),
        ),
    ]
