# Generated by Django 3.0.4 on 2020-03-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200321_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='player_2',
            new_name='looser',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='score_player_1',
            new_name='looser_points',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='player_1',
            new_name='winner',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='score_player_2',
            new_name='winner_points',
        ),
    ]
