# Generated by Django 3.0.4 on 2020-03-21 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200321_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='looser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
