# Generated by Django 3.0.4 on 2020-03-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_history_null_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
