# Generated by Django 3.0.4 on 2020-03-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_history_poule'),
        ('users', '0008_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='pool_players', to='matching.Poule'),
        ),
    ]
