# Generated by Django 3.0.4 on 2020-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200323_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identifiant',
            field=models.CharField(max_length=150, verbose_name='platform username'),
        ),
    ]
