# Generated by Django 3.0.4 on 2020-03-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_history_poule'),
        ('users', '0011_auto_20200324_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_players', to='matching.Poule'),
        ),
    ]
