# Generated by Django 3.0.4 on 2020-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(choices=[('a', 'PS4'), ('b', 'XBOX')], default='a', max_length=1, verbose_name="Player's platform"),
        ),
    ]
