# Generated by Django 3.0.4 on 2020-03-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fr_text', models.TextField()),
                ('en_text', models.TextField()),
                ('nl_text', models.TextField()),
            ],
        ),
    ]
