# Generated by Django 3.0.4 on 2020-03-24 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotten_pass',
            name='link_active',
        ),
        migrations.AddField(
            model_name='forgotten_pass',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
