# Generated by Django 3.0.4 on 2020-03-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_poule'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='poule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='related_pool', to='matching.Poule'),
        ),
    ]
