# Generated by Django 3.0.4 on 2020-03-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_poule_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poule',
            name='platform',
            field=models.CharField(choices=[('ps4', 'PS4'), ('xbox', 'XBOX')], default='ps4', max_length=4, verbose_name='platforme'),
        ),
    ]
