# Generated by Django 3.0.4 on 2020-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_history_poule'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
