# Generated by Django 3.0.4 on 2020-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20200331_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_played',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
